# Book settings
title: "Convex Optimization: A Practical Guide"
author: "Behzad Samadi"
logo: logo.png

# Information about where the book exists on the web
repository:
  url                       : https://github.com/bsamadi/cvxguide  # Online location of your book
  book_path                 : cvxguidebook  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)

execute:
  execute_notebooks: auto
  
latex:
  latex_documents:
    targetname: cvxguide.tex

sphinx:
  extra_extensions          : ""
  config                    :
    mathjax_config          :
      TeX                   :
        Macros              :
          "sign"            : "\\mathop{\\rm sgn}\nolimits"
          "CO"              : "{\\textbf{\\rm conv}}"
          "RR"              : "{{\\mathcal R}}"
          "RE"              : "{\\mathbb{R}}"
          "TR"              : "{\\text{T}}"
          "beq"             : "{\\begin{equation}}"
          "eeq"             : "{\\end{equation}}"
          "bmat"            : "{\\begin{bmatrix}}"
          "emat"            : "{\\end{bmatrix}}"
          "bsmat"           : "{\\left[\\begin{smallmatrix}}"
          "esmat"           : "{\\end{smallmatrix}\\right]}"
          "barr"            : "{\\begin{array}}"
          "earr"            : "{\\end{array}}"
          "bsm"             : "{\\begin{smallmatrix}}"
          "esm"             : "{\\end{smallmatrix}}"
