name: Jupyter Book CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: python-3.7
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Virtual environment
        run: |
             python -V
             pip install virtualenv
             virtualenv venv
             source venv/bin/activate


      - name: Install Jupyter Book
        run: pip install -U "jupyter-book>=0.7.0b"
        
      - name: Build
        run: jupyter-book build cvxguidebook/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cvxguidebook/_build/html
